name: ci

on:
  push:
    paths:
      - "**.c"
      - "**.cmake"
      - "**/CMakeLists.txt"
      - ".github/workflows/ci.yml"

jobs:

  unix:

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        intsize: [32, 64]

    runs-on: ${{ matrix.os }}
    timeout-minutes: 5

    steps:
    - uses: actions/checkout@v4

    - run: cmake -B build -DIDXTYPEWIDTH=${{ matrix.intsize }}
    - run: cmake --build build --parallel

    - run: ctest --test-dir build -V


  windows_msvc:
    runs-on: windows-latest
    timeout-minutes: 5

    steps:
    - uses: actions/checkout@v4

    - run: cmake -B build

    - run: cmake --build build --config Release --parallel

    - run: ctest --test-dir build -C Release -V
